apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-in-cluster
  namespace: kube-system
stringData:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - name: ${cluster_name}
      cluster:
        server: ${server}
        certificate-authority-data: ${kube_ca_cert}
    users:
    - name: service-account
      user:
        # Use service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: ${cluster_name}
        user: service-account
